# coding: utf-8

"""
    Share House Portal API

    This OpenAPI document captures the request and response models implemented under `app/api/**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from share_house_portal_sdk.models.notification_list_response import NotificationListResponse

class TestNotificationListResponse(unittest.TestCase):
    """NotificationListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationListResponse:
        """Test NotificationListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationListResponse`
        """
        model = NotificationListResponse()
        if include_optional:
            return NotificationListResponse(
                data = [
                    share_house_portal_sdk.models.notification.Notification(
                        id = '', 
                        user_id = '', 
                        title = '', 
                        message = '', 
                        type = 'info', 
                        action_url = '', 
                        metadata = null, 
                        read = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = share_house_portal_sdk.models.notification_pagination.NotificationPagination(
                    page = 56, 
                    limit = 56, 
                    total = 56, 
                    has_more = True, ),
                filters = share_house_portal_sdk.models.notification_filters.NotificationFilters(
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return NotificationListResponse(
                data = [
                    share_house_portal_sdk.models.notification.Notification(
                        id = '', 
                        user_id = '', 
                        title = '', 
                        message = '', 
                        type = 'info', 
                        action_url = '', 
                        metadata = null, 
                        read = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = share_house_portal_sdk.models.notification_pagination.NotificationPagination(
                    page = 56, 
                    limit = 56, 
                    total = 56, 
                    has_more = True, ),
                filters = share_house_portal_sdk.models.notification_filters.NotificationFilters(
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testNotificationListResponse(self):
        """Test NotificationListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
