# coding: utf-8

"""
    Share House Portal API

    This OpenAPI document captures the request and response models implemented under `app/api/**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from share_house_portal_sdk.models.validation_error_response import ValidationErrorResponse

class TestValidationErrorResponse(unittest.TestCase):
    """ValidationErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationErrorResponse:
        """Test ValidationErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationErrorResponse`
        """
        model = ValidationErrorResponse()
        if include_optional:
            return ValidationErrorResponse(
                error = '',
                details = { }
            )
        else:
            return ValidationErrorResponse(
                error = '',
        )
        """

    def testValidationErrorResponse(self):
        """Test ValidationErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
