# coding: utf-8

"""
    Share House Portal API

    This OpenAPI document captures the request and response models implemented under `app/api/**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from share_house_portal_sdk.models.document_list_response import DocumentListResponse

class TestDocumentListResponse(unittest.TestCase):
    """DocumentListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentListResponse:
        """Test DocumentListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentListResponse`
        """
        model = DocumentListResponse()
        if include_optional:
            return DocumentListResponse(
                documents = [
                    share_house_portal_sdk.models.document_record.DocumentRecord(
                        id = '', 
                        title = '', 
                        status = 'draft', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tenant_id = '', )
                    ],
                meta = share_house_portal_sdk.models.document_list_meta.DocumentListMeta(
                    count = 56, 
                    latest_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    revision = 'current', )
            )
        else:
            return DocumentListResponse(
                documents = [
                    share_house_portal_sdk.models.document_record.DocumentRecord(
                        id = '', 
                        title = '', 
                        status = 'draft', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tenant_id = '', )
                    ],
                meta = share_house_portal_sdk.models.document_list_meta.DocumentListMeta(
                    count = 56, 
                    latest_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    revision = 'current', ),
        )
        """

    def testDocumentListResponse(self):
        """Test DocumentListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
