# coding: utf-8

"""
    Share House Portal API

    This OpenAPI document captures the request and response models implemented under `app/api/**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from share_house_portal_sdk.models.payment_receipt_request import PaymentReceiptRequest

class TestPaymentReceiptRequest(unittest.TestCase):
    """PaymentReceiptRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentReceiptRequest:
        """Test PaymentReceiptRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentReceiptRequest`
        """
        model = PaymentReceiptRequest()
        if include_optional:
            return PaymentReceiptRequest(
                customer_email = '',
                customer_name = '',
                payment_id = '',
                amount_paid = 1.337,
                currency = '',
                payment_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                items = [
                    share_house_portal_sdk.models.payment_line_item.PaymentLineItem(
                        description = '', 
                        quantity = 1.337, 
                        unit_amount = 1.337, 
                        total_amount = 1.337, )
                    ],
                business_name = '',
                support_email = '',
                billing_address = '',
                notes = '',
                subtotal_amount = 1.337,
                tax_amount = 1.337,
                discount_amount = 1.337,
                send_copy_to = [
                    ''
                    ]
            )
        else:
            return PaymentReceiptRequest(
                customer_email = '',
                customer_name = '',
                payment_id = '',
                amount_paid = 1.337,
                currency = '',
        )
        """

    def testPaymentReceiptRequest(self):
        """Test PaymentReceiptRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
