import type { SharedLedgerPurchase } from "@/types/supplies"

export const sharedLedgerEntries: SharedLedgerPurchase[] = [
  {
    id: "purchase-2024-05-31-costco",
    description: "Costco bulk household restock",
    category: "Groceries & supplies",
    merchant: "Costco",
    purchasedAt: "2024-05-31T16:30:00Z",
    paidBy: { id: "rm_priya", name: "Priya Desai" },
    totalAmount: 189.72,
    currency: "USD",
    note: "Restocked paper towels, detergent, and snacks for the month.",
    shares: [
      { roommateId: "rm_priya", roommateName: "Priya Desai", amount: 63.24 },
      { roommateId: "rm_avery", roommateName: "Avery Chen", amount: 63.24 },
      { roommateId: "rm_jordan", roommateName: "Jordan Blake", amount: 63.24 },
    ],
  },
  {
    id: "purchase-2024-06-03-target",
    description: "Target cleaning haul",
    category: "Cleaning",
    merchant: "Target",
    purchasedAt: "2024-06-03T18:45:00Z",
    paidBy: { id: "rm_avery", name: "Avery Chen" },
    totalAmount: 54.18,
    currency: "USD",
    note: "Mop refills, all-purpose spray, and compostable trash bags.",
    shares: [
      { roommateId: "rm_avery", roommateName: "Avery Chen", amount: 18.06 },
      { roommateId: "rm_jordan", roommateName: "Jordan Blake", amount: 18.06 },
      { roommateId: "rm_priya", roommateName: "Priya Desai", amount: 18.06 },
    ],
  },
  {
    id: "purchase-2024-06-12-farmers",
    description: "Farmer's market produce top-up",
    category: "Groceries",
    merchant: "Downtown Farmer's Market",
    purchasedAt: "2024-06-12T01:20:00Z",
    paidBy: { id: "rm_jordan", name: "Jordan Blake" },
    totalAmount: 36.5,
    currency: "USD",
    note: "Berries for brunch and a fresh bag of coffee beans.",
    shares: [
      { roommateId: "rm_jordan", roommateName: "Jordan Blake", amount: 12.17 },
      { roommateId: "rm_avery", roommateName: "Avery Chen", amount: 12.17 },
      { roommateId: "rm_priya", roommateName: "Priya Desai", amount: 12.16 },
    ],
  },
  {
    id: "purchase-2024-06-30-late-night",
    description: "Late-night grocery run",
    category: "Groceries",
    merchant: "24hr Neighborhood Market",
    purchasedAt: "2024-07-01T06:45:00Z",
    paidBy: { id: "rm_avery", name: "Avery Chen" },
    totalAmount: 28.33,
    currency: "USD",
    note: "Milk, cereal, and oat milk restock after the weekend guests.",
    shares: [
      { roommateId: "rm_avery", roommateName: "Avery Chen", amount: 9.44 },
      { roommateId: "rm_jordan", roommateName: "Jordan Blake", amount: 9.45 },
      { roommateId: "rm_priya", roommateName: "Priya Desai", amount: 9.44 },
    ],
  },
  {
    id: "purchase-2024-07-04-bbq",
    description: "Fourth of July BBQ supplies",
    category: "Entertaining",
    merchant: "Whole Foods",
    purchasedAt: "2024-07-04T15:10:00Z",
    paidBy: { id: "rm_priya", name: "Priya Desai" },
    totalAmount: 96.27,
    currency: "USD",
    note: "Veggie skewers, drinks, and condiments for the rooftop cookout.",
    shares: [
      { roommateId: "rm_priya", roommateName: "Priya Desai", amount: 32.09 },
      { roommateId: "rm_avery", roommateName: "Avery Chen", amount: 32.09 },
      { roommateId: "rm_jordan", roommateName: "Jordan Blake", amount: 32.09 },
    ],
  },
]
