export type MemberSearchExpectation = {
  /** Query string as typed by end users (case insensitive). */
  query: string
  /** Member profile identifiers that must appear in the first page of results. */
  expectedEntityIds: string[]
}

const seededExpectations: MemberSearchExpectation[] = [
  {
    query: 'property manager',
    expectedEntityIds: ['profile-property-manager'],
  },
  {
    query: 'tenant onboarding',
    expectedEntityIds: ['profile-tenant-onboarding-lead'],
  },
  {
    query: 'unit 2a',
    expectedEntityIds: ['unit-2a-steward'],
  },
  {
    query: 'lease signer',
    expectedEntityIds: ['profile-lease-signer'],
  },
  {
    query: 'maintenance lead',
    expectedEntityIds: ['profile-maintenance-lead'],
  },
  {
    query: 'evening concierge',
    expectedEntityIds: ['profile-concierge-evening'],
  },
  {
    query: 'weekend manager',
    expectedEntityIds: ['profile-weekend-manager'],
  },
  {
    query: 'resident advisor',
    expectedEntityIds: ['profile-resident-advisor'],
  },
  {
    query: 'parking coordinator',
    expectedEntityIds: ['profile-parking-coordinator'],
  },
  {
    query: 'guest liaison',
    expectedEntityIds: ['profile-guest-liaison'],
  },
]

const autoGeneratedExpectations: MemberSearchExpectation[] = Array.from(
  { length: 90 },
  (_, index) => {
    const suffix = String(index + 1).padStart(3, '0')
    return {
      query: `unit ${suffix}`,
      expectedEntityIds: [`unit-${suffix}-primary-contact`],
    }
  }
)

export const TOP_MEMBER_SEARCH_QUERIES: MemberSearchExpectation[] = [
  ...seededExpectations,
  ...autoGeneratedExpectations,
]
