/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingPortalResponse
 */
export interface BillingPortalResponse {
    /**
     * 
     * @type {string}
     * @memberof BillingPortalResponse
     */
    url: string;
}

/**
 * Check if a given object implements the BillingPortalResponse interface.
 */
export function instanceOfBillingPortalResponse(value: object): value is BillingPortalResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function BillingPortalResponseFromJSON(json: any): BillingPortalResponse {
    return BillingPortalResponseFromJSONTyped(json, false);
}

export function BillingPortalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPortalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function BillingPortalResponseToJSON(json: any): BillingPortalResponse {
    return BillingPortalResponseToJSONTyped(json, false);
}

export function BillingPortalResponseToJSONTyped(value?: BillingPortalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

