/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingPortalRequest
 */
export interface BillingPortalRequest {
    /**
     * 
     * @type {string}
     * @memberof BillingPortalRequest
     */
    customerId: string;
}

/**
 * Check if a given object implements the BillingPortalRequest interface.
 */
export function instanceOfBillingPortalRequest(value: object): value is BillingPortalRequest {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function BillingPortalRequestFromJSON(json: any): BillingPortalRequest {
    return BillingPortalRequestFromJSONTyped(json, false);
}

export function BillingPortalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPortalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customerId'],
    };
}

export function BillingPortalRequestToJSON(json: any): BillingPortalRequest {
    return BillingPortalRequestToJSONTyped(json, false);
}

export function BillingPortalRequestToJSONTyped(value?: BillingPortalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerId': value['customerId'],
    };
}

