/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionRequest
 */
export interface CheckoutSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionRequest
     */
    priceId: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutSessionRequest
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionRequest
     */
    mode?: CheckoutSessionRequestModeEnum;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CheckoutSessionRequest
     */
    metadata?: { [key: string]: string; };
}


/**
 * @export
 */
export const CheckoutSessionRequestModeEnum = {
    Payment: 'payment',
    Subscription: 'subscription'
} as const;
export type CheckoutSessionRequestModeEnum = typeof CheckoutSessionRequestModeEnum[keyof typeof CheckoutSessionRequestModeEnum];


/**
 * Check if a given object implements the CheckoutSessionRequest interface.
 */
export function instanceOfCheckoutSessionRequest(value: object): value is CheckoutSessionRequest {
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    return true;
}

export function CheckoutSessionRequestFromJSON(json: any): CheckoutSessionRequest {
    return CheckoutSessionRequestFromJSONTyped(json, false);
}

export function CheckoutSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['priceId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CheckoutSessionRequestToJSON(json: any): CheckoutSessionRequest {
    return CheckoutSessionRequestToJSONTyped(json, false);
}

export function CheckoutSessionRequestToJSONTyped(value?: CheckoutSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceId': value['priceId'],
        'quantity': value['quantity'],
        'mode': value['mode'],
        'metadata': value['metadata'],
    };
}

