/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionResponse
 */
export interface CheckoutSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionResponse
     */
    url: string;
}

/**
 * Check if a given object implements the CheckoutSessionResponse interface.
 */
export function instanceOfCheckoutSessionResponse(value: object): value is CheckoutSessionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CheckoutSessionResponseFromJSON(json: any): CheckoutSessionResponse {
    return CheckoutSessionResponseFromJSONTyped(json, false);
}

export function CheckoutSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
    };
}

export function CheckoutSessionResponseToJSON(json: any): CheckoutSessionResponse {
    return CheckoutSessionResponseToJSONTyped(json, false);
}

export function CheckoutSessionResponseToJSONTyped(value?: CheckoutSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

