/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentRecord } from './DocumentRecord';
import {
    DocumentRecordFromJSON,
    DocumentRecordFromJSONTyped,
    DocumentRecordToJSON,
    DocumentRecordToJSONTyped,
} from './DocumentRecord';
import type { DocumentListMeta } from './DocumentListMeta';
import {
    DocumentListMetaFromJSON,
    DocumentListMetaFromJSONTyped,
    DocumentListMetaToJSON,
    DocumentListMetaToJSONTyped,
} from './DocumentListMeta';

/**
 * 
 * @export
 * @interface DocumentListResponse
 */
export interface DocumentListResponse {
    /**
     * 
     * @type {Array<DocumentRecord>}
     * @memberof DocumentListResponse
     */
    documents: Array<DocumentRecord>;
    /**
     * 
     * @type {DocumentListMeta}
     * @memberof DocumentListResponse
     */
    meta: DocumentListMeta;
}

/**
 * Check if a given object implements the DocumentListResponse interface.
 */
export function instanceOfDocumentListResponse(value: object): value is DocumentListResponse {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function DocumentListResponseFromJSON(json: any): DocumentListResponse {
    return DocumentListResponseFromJSONTyped(json, false);
}

export function DocumentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(DocumentRecordFromJSON)),
        'meta': DocumentListMetaFromJSON(json['meta']),
    };
}

export function DocumentListResponseToJSON(json: any): DocumentListResponse {
    return DocumentListResponseToJSONTyped(json, false);
}

export function DocumentListResponseToJSONTyped(value?: DocumentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documents': ((value['documents'] as Array<any>).map(DocumentRecordToJSON)),
        'meta': DocumentListMetaToJSON(value['meta']),
    };
}

