/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentRecord
 */
export interface DocumentRecord {
    /**
     * 
     * @type {string}
     * @memberof DocumentRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRecord
     */
    status: DocumentRecordStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof DocumentRecord
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DocumentRecord
     */
    tenantId: string;
}


/**
 * @export
 */
export const DocumentRecordStatusEnum = {
    Draft: 'draft',
    PendingSignature: 'pending_signature',
    Signed: 'signed',
    Expired: 'expired',
    Cancelled: 'cancelled'
} as const;
export type DocumentRecordStatusEnum = typeof DocumentRecordStatusEnum[keyof typeof DocumentRecordStatusEnum];


/**
 * Check if a given object implements the DocumentRecord interface.
 */
export function instanceOfDocumentRecord(value: object): value is DocumentRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function DocumentRecordFromJSON(json: any): DocumentRecord {
    return DocumentRecordFromJSONTyped(json, false);
}

export function DocumentRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'status': json['status'],
        'updatedAt': (new Date(json['updated_at'])),
        'tenantId': json['tenant_id'],
    };
}

export function DocumentRecordToJSON(json: any): DocumentRecord {
    return DocumentRecordToJSONTyped(json, false);
}

export function DocumentRecordToJSONTyped(value?: DocumentRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'status': value['status'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'tenant_id': value['tenantId'],
    };
}

