/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentListMeta
 */
export interface DocumentListMeta {
    /**
     * 
     * @type {number}
     * @memberof DocumentListMeta
     */
    count: number;
    /**
     * 
     * @type {Date}
     * @memberof DocumentListMeta
     */
    latestUpdatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof DocumentListMeta
     */
    revision: DocumentListMetaRevisionEnum;
}


/**
 * @export
 */
export const DocumentListMetaRevisionEnum = {
    Current: 'current',
    Revision2: 'revision2'
} as const;
export type DocumentListMetaRevisionEnum = typeof DocumentListMetaRevisionEnum[keyof typeof DocumentListMetaRevisionEnum];


/**
 * Check if a given object implements the DocumentListMeta interface.
 */
export function instanceOfDocumentListMeta(value: object): value is DocumentListMeta {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('latestUpdatedAt' in value) || value['latestUpdatedAt'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function DocumentListMetaFromJSON(json: any): DocumentListMeta {
    return DocumentListMetaFromJSONTyped(json, false);
}

export function DocumentListMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentListMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'latestUpdatedAt': (new Date(json['latestUpdatedAt'])),
        'revision': json['revision'],
    };
}

export function DocumentListMetaToJSON(json: any): DocumentListMeta {
    return DocumentListMetaToJSONTyped(json, false);
}

export function DocumentListMetaToJSONTyped(value?: DocumentListMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'latestUpdatedAt': ((value['latestUpdatedAt']).toISOString()),
        'revision': value['revision'],
    };
}

