/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailRecipient } from './EmailRecipient';
import {
    EmailRecipientFromJSON,
    EmailRecipientFromJSONTyped,
    EmailRecipientToJSON,
    EmailRecipientToJSONTyped,
} from './EmailRecipient';

/**
 * 
 * @export
 * @interface EmailNotificationData
 */
export interface EmailNotificationData {
    /**
     * 
     * @type {EmailRecipient}
     * @memberof EmailNotificationData
     */
    to: EmailRecipient;
    /**
     * 
     * @type {string}
     * @memberof EmailNotificationData
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof EmailNotificationData
     */
    template: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EmailNotificationData
     */
    data?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof EmailNotificationData
     */
    userId?: string;
}

/**
 * Check if a given object implements the EmailNotificationData interface.
 */
export function instanceOfEmailNotificationData(value: object): value is EmailNotificationData {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function EmailNotificationDataFromJSON(json: any): EmailNotificationData {
    return EmailNotificationDataFromJSONTyped(json, false);
}

export function EmailNotificationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailNotificationData {
    if (json == null) {
        return json;
    }
    return {
        
        'to': EmailRecipientFromJSON(json['to']),
        'subject': json['subject'],
        'template': json['template'],
        'data': json['data'] == null ? undefined : json['data'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function EmailNotificationDataToJSON(json: any): EmailNotificationData {
    return EmailNotificationDataToJSONTyped(json, false);
}

export function EmailNotificationDataToJSONTyped(value?: EmailNotificationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': EmailRecipientToJSON(value['to']),
        'subject': value['subject'],
        'template': value['template'],
        'data': value['data'],
        'userId': value['userId'],
    };
}

