/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type EmailRecipient
 * 
 * @export
 */
export type EmailRecipient = Array<string> | string;

export function EmailRecipientFromJSON(json: any): EmailRecipient {
    return EmailRecipientFromJSONTyped(json, false);
}

export function EmailRecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailRecipient {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function EmailRecipientToJSON(json: any): any {
    return EmailRecipientToJSONTyped(json, false);
}

export function EmailRecipientToJSONTyped(value?: EmailRecipient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

