/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InAppNotificationData
 */
export interface InAppNotificationData {
    /**
     * 
     * @type {string}
     * @memberof InAppNotificationData
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof InAppNotificationData
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof InAppNotificationData
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof InAppNotificationData
     */
    type: InAppNotificationDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InAppNotificationData
     */
    actionUrl?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InAppNotificationData
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const InAppNotificationDataTypeEnum = {
    Info: 'info',
    Success: 'success',
    Warning: 'warning',
    Error: 'error'
} as const;
export type InAppNotificationDataTypeEnum = typeof InAppNotificationDataTypeEnum[keyof typeof InAppNotificationDataTypeEnum];


/**
 * Check if a given object implements the InAppNotificationData interface.
 */
export function instanceOfInAppNotificationData(value: object): value is InAppNotificationData {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function InAppNotificationDataFromJSON(json: any): InAppNotificationData {
    return InAppNotificationDataFromJSONTyped(json, false);
}

export function InAppNotificationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppNotificationData {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'title': json['title'],
        'message': json['message'],
        'type': json['type'],
        'actionUrl': json['actionUrl'] == null ? undefined : json['actionUrl'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function InAppNotificationDataToJSON(json: any): InAppNotificationData {
    return InAppNotificationDataToJSONTyped(json, false);
}

export function InAppNotificationDataToJSONTyped(value?: InAppNotificationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'title': value['title'],
        'message': value['message'],
        'type': value['type'],
        'actionUrl': value['actionUrl'],
        'metadata': value['metadata'],
    };
}

