/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailNotificationData } from './EmailNotificationData';
import {
    EmailNotificationDataFromJSON,
    EmailNotificationDataFromJSONTyped,
    EmailNotificationDataToJSON,
    EmailNotificationDataToJSONTyped,
} from './EmailNotificationData';

/**
 * 
 * @export
 * @interface NotificationEmailRequest
 */
export interface NotificationEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationEmailRequest
     */
    type: NotificationEmailRequestTypeEnum;
    /**
     * 
     * @type {EmailNotificationData}
     * @memberof NotificationEmailRequest
     */
    notification: EmailNotificationData;
}


/**
 * @export
 */
export const NotificationEmailRequestTypeEnum = {
    Email: 'email'
} as const;
export type NotificationEmailRequestTypeEnum = typeof NotificationEmailRequestTypeEnum[keyof typeof NotificationEmailRequestTypeEnum];


/**
 * Check if a given object implements the NotificationEmailRequest interface.
 */
export function instanceOfNotificationEmailRequest(value: object): value is NotificationEmailRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('notification' in value) || value['notification'] === undefined) return false;
    return true;
}

export function NotificationEmailRequestFromJSON(json: any): NotificationEmailRequest {
    return NotificationEmailRequestFromJSONTyped(json, false);
}

export function NotificationEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'notification': EmailNotificationDataFromJSON(json['notification']),
    };
}

export function NotificationEmailRequestToJSON(json: any): NotificationEmailRequest {
    return NotificationEmailRequestToJSONTyped(json, false);
}

export function NotificationEmailRequestToJSONTyped(value?: NotificationEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'notification': EmailNotificationDataToJSON(value['notification']),
    };
}

