/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InAppNotificationData } from './InAppNotificationData';
import {
    InAppNotificationDataFromJSON,
    InAppNotificationDataFromJSONTyped,
    InAppNotificationDataToJSON,
    InAppNotificationDataToJSONTyped,
} from './InAppNotificationData';

/**
 * 
 * @export
 * @interface NotificationInAppRequest
 */
export interface NotificationInAppRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationInAppRequest
     */
    type: NotificationInAppRequestTypeEnum;
    /**
     * 
     * @type {InAppNotificationData}
     * @memberof NotificationInAppRequest
     */
    notification: InAppNotificationData;
}


/**
 * @export
 */
export const NotificationInAppRequestTypeEnum = {
    InApp: 'in-app'
} as const;
export type NotificationInAppRequestTypeEnum = typeof NotificationInAppRequestTypeEnum[keyof typeof NotificationInAppRequestTypeEnum];


/**
 * Check if a given object implements the NotificationInAppRequest interface.
 */
export function instanceOfNotificationInAppRequest(value: object): value is NotificationInAppRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('notification' in value) || value['notification'] === undefined) return false;
    return true;
}

export function NotificationInAppRequestFromJSON(json: any): NotificationInAppRequest {
    return NotificationInAppRequestFromJSONTyped(json, false);
}

export function NotificationInAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationInAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'notification': InAppNotificationDataFromJSON(json['notification']),
    };
}

export function NotificationInAppRequestToJSON(json: any): NotificationInAppRequest {
    return NotificationInAppRequestToJSONTyped(json, false);
}

export function NotificationInAppRequestToJSONTyped(value?: NotificationInAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'notification': InAppNotificationDataToJSON(value['notification']),
    };
}

