/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationBulkResultError } from './NotificationBulkResultError';
import {
    NotificationBulkResultErrorFromJSON,
    NotificationBulkResultErrorFromJSONTyped,
    NotificationBulkResultErrorToJSON,
    NotificationBulkResultErrorToJSONTyped,
} from './NotificationBulkResultError';

/**
 * 
 * @export
 * @interface NotificationBulkResult
 */
export interface NotificationBulkResult {
    /**
     * 
     * @type {number}
     * @memberof NotificationBulkResult
     */
    index?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationBulkResult
     */
    success?: boolean;
    /**
     * 
     * @type {NotificationBulkResultError}
     * @memberof NotificationBulkResult
     */
    error?: NotificationBulkResultError;
}

/**
 * Check if a given object implements the NotificationBulkResult interface.
 */
export function instanceOfNotificationBulkResult(value: object): value is NotificationBulkResult {
    return true;
}

export function NotificationBulkResultFromJSON(json: any): NotificationBulkResult {
    return NotificationBulkResultFromJSONTyped(json, false);
}

export function NotificationBulkResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationBulkResult {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : NotificationBulkResultErrorFromJSON(json['error']),
    };
}

export function NotificationBulkResultToJSON(json: any): NotificationBulkResult {
    return NotificationBulkResultToJSONTyped(json, false);
}

export function NotificationBulkResultToJSONTyped(value?: NotificationBulkResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'success': value['success'],
        'error': NotificationBulkResultErrorToJSON(value['error']),
    };
}

