/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationBulkRequestNotificationsInner } from './NotificationBulkRequestNotificationsInner';
import {
    NotificationBulkRequestNotificationsInnerFromJSON,
    NotificationBulkRequestNotificationsInnerFromJSONTyped,
    NotificationBulkRequestNotificationsInnerToJSON,
    NotificationBulkRequestNotificationsInnerToJSONTyped,
} from './NotificationBulkRequestNotificationsInner';

/**
 * 
 * @export
 * @interface NotificationBulkRequest
 */
export interface NotificationBulkRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationBulkRequest
     */
    type: NotificationBulkRequestTypeEnum;
    /**
     * 
     * @type {Array<NotificationBulkRequestNotificationsInner>}
     * @memberof NotificationBulkRequest
     */
    notifications: Array<NotificationBulkRequestNotificationsInner>;
}


/**
 * @export
 */
export const NotificationBulkRequestTypeEnum = {
    Bulk: 'bulk'
} as const;
export type NotificationBulkRequestTypeEnum = typeof NotificationBulkRequestTypeEnum[keyof typeof NotificationBulkRequestTypeEnum];


/**
 * Check if a given object implements the NotificationBulkRequest interface.
 */
export function instanceOfNotificationBulkRequest(value: object): value is NotificationBulkRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('notifications' in value) || value['notifications'] === undefined) return false;
    return true;
}

export function NotificationBulkRequestFromJSON(json: any): NotificationBulkRequest {
    return NotificationBulkRequestFromJSONTyped(json, false);
}

export function NotificationBulkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationBulkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'notifications': ((json['notifications'] as Array<any>).map(NotificationBulkRequestNotificationsInnerFromJSON)),
    };
}

export function NotificationBulkRequestToJSON(json: any): NotificationBulkRequest {
    return NotificationBulkRequestToJSONTyped(json, false);
}

export function NotificationBulkRequestToJSONTyped(value?: NotificationBulkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'notifications': ((value['notifications'] as Array<any>).map(NotificationBulkRequestNotificationsInnerToJSON)),
    };
}

