/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationFilters
 */
export interface NotificationFilters {
    /**
     * 
     * @type {Date}
     * @memberof NotificationFilters
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof NotificationFilters
     */
    endDate: Date;
}

/**
 * Check if a given object implements the NotificationFilters interface.
 */
export function instanceOfNotificationFilters(value: object): value is NotificationFilters {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function NotificationFiltersFromJSON(json: any): NotificationFilters {
    return NotificationFiltersFromJSONTyped(json, false);
}

export function NotificationFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
    };
}

export function NotificationFiltersToJSON(json: any): NotificationFilters {
    return NotificationFiltersToJSONTyped(json, false);
}

export function NotificationFiltersToJSONTyped(value?: NotificationFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': ((value['startDate']).toISOString()),
        'endDate': ((value['endDate']).toISOString()),
    };
}

