/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type NotificationBulkResultError
 * Error message or provider payload when a bulk request entry failed.
 * @export
 */
export type NotificationBulkResultError = string | { [key: string]: any; };

export function NotificationBulkResultErrorFromJSON(json: any): NotificationBulkResultError {
    return NotificationBulkResultErrorFromJSONTyped(json, false);
}

export function NotificationBulkResultErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationBulkResultError {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function NotificationBulkResultErrorToJSON(json: any): any {
    return NotificationBulkResultErrorToJSONTyped(json, false);
}

export function NotificationBulkResultErrorToJSONTyped(value?: NotificationBulkResultError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

