/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EmailNotificationData } from './EmailNotificationData';
import {
    instanceOfEmailNotificationData,
    EmailNotificationDataFromJSON,
    EmailNotificationDataFromJSONTyped,
    EmailNotificationDataToJSON,
} from './EmailNotificationData';
import type { InAppNotificationData } from './InAppNotificationData';
import {
    instanceOfInAppNotificationData,
    InAppNotificationDataFromJSON,
    InAppNotificationDataFromJSONTyped,
    InAppNotificationDataToJSON,
} from './InAppNotificationData';

/**
 * @type NotificationBulkRequestNotificationsInner
 * 
 * @export
 */
export type NotificationBulkRequestNotificationsInner = EmailNotificationData | InAppNotificationData;

export function NotificationBulkRequestNotificationsInnerFromJSON(json: any): NotificationBulkRequestNotificationsInner {
    return NotificationBulkRequestNotificationsInnerFromJSONTyped(json, false);
}

export function NotificationBulkRequestNotificationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationBulkRequestNotificationsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEmailNotificationData(json)) {
        return EmailNotificationDataFromJSONTyped(json, true);
    }
    if (instanceOfInAppNotificationData(json)) {
        return InAppNotificationDataFromJSONTyped(json, true);
    }

    return {} as any;
}

export function NotificationBulkRequestNotificationsInnerToJSON(json: any): any {
    return NotificationBulkRequestNotificationsInnerToJSONTyped(json, false);
}

export function NotificationBulkRequestNotificationsInnerToJSONTyped(value?: NotificationBulkRequestNotificationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEmailNotificationData(value)) {
        return EmailNotificationDataToJSON(value as EmailNotificationData);
    }
    if (instanceOfInAppNotificationData(value)) {
        return InAppNotificationDataToJSON(value as InAppNotificationData);
    }

    return {};
}

