/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationPagination } from './NotificationPagination';
import {
    NotificationPaginationFromJSON,
    NotificationPaginationFromJSONTyped,
    NotificationPaginationToJSON,
    NotificationPaginationToJSONTyped,
} from './NotificationPagination';
import type { NotificationFilters } from './NotificationFilters';
import {
    NotificationFiltersFromJSON,
    NotificationFiltersFromJSONTyped,
    NotificationFiltersToJSON,
    NotificationFiltersToJSONTyped,
} from './NotificationFilters';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface NotificationListResponse
 */
export interface NotificationListResponse {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof NotificationListResponse
     */
    data: Array<Notification>;
    /**
     * 
     * @type {NotificationPagination}
     * @memberof NotificationListResponse
     */
    pagination: NotificationPagination;
    /**
     * 
     * @type {NotificationFilters}
     * @memberof NotificationListResponse
     */
    filters: NotificationFilters;
}

/**
 * Check if a given object implements the NotificationListResponse interface.
 */
export function instanceOfNotificationListResponse(value: object): value is NotificationListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    return true;
}

export function NotificationListResponseFromJSON(json: any): NotificationListResponse {
    return NotificationListResponseFromJSONTyped(json, false);
}

export function NotificationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(NotificationFromJSON)),
        'pagination': NotificationPaginationFromJSON(json['pagination']),
        'filters': NotificationFiltersFromJSON(json['filters']),
    };
}

export function NotificationListResponseToJSON(json: any): NotificationListResponse {
    return NotificationListResponseToJSONTyped(json, false);
}

export function NotificationListResponseToJSONTyped(value?: NotificationListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(NotificationToJSON)),
        'pagination': NotificationPaginationToJSON(value['pagination']),
        'filters': NotificationFiltersToJSON(value['filters']),
    };
}

