/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationBulkResult } from './NotificationBulkResult';
import {
    NotificationBulkResultFromJSON,
    NotificationBulkResultFromJSONTyped,
    NotificationBulkResultToJSON,
    NotificationBulkResultToJSONTyped,
} from './NotificationBulkResult';

/**
 * 
 * @export
 * @interface NotificationDispatchResponse
 */
export interface NotificationDispatchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDispatchResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationDispatchResponse
     */
    error?: string;
    /**
     * 
     * @type {any}
     * @memberof NotificationDispatchResponse
     */
    data?: any | null;
    /**
     * 
     * @type {Array<NotificationBulkResult>}
     * @memberof NotificationDispatchResponse
     */
    results?: Array<NotificationBulkResult>;
}

/**
 * Check if a given object implements the NotificationDispatchResponse interface.
 */
export function instanceOfNotificationDispatchResponse(value: object): value is NotificationDispatchResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function NotificationDispatchResponseFromJSON(json: any): NotificationDispatchResponse {
    return NotificationDispatchResponseFromJSONTyped(json, false);
}

export function NotificationDispatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDispatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'data': json['data'] == null ? undefined : json['data'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(NotificationBulkResultFromJSON)),
    };
}

export function NotificationDispatchResponseToJSON(json: any): NotificationDispatchResponse {
    return NotificationDispatchResponseToJSONTyped(json, false);
}

export function NotificationDispatchResponseToJSONTyped(value?: NotificationDispatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'data': value['data'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(NotificationBulkResultToJSON)),
    };
}

