/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type NotificationDispatchRequest
 * 
 * @export
 */
export type NotificationDispatchRequest = { type: 'bulk' } & NotificationBulkRequest | { type: 'email' } & NotificationEmailRequest | { type: 'in-app' } & NotificationInAppRequest;

export function NotificationDispatchRequestFromJSON(json: any): NotificationDispatchRequest {
    return NotificationDispatchRequestFromJSONTyped(json, false);
}

export function NotificationDispatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDispatchRequest {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'bulk':
            return Object.assign({}, NotificationBulkRequestFromJSONTyped(json, true), { type: 'bulk' } as const);
        case 'email':
            return Object.assign({}, NotificationEmailRequestFromJSONTyped(json, true), { type: 'email' } as const);
        case 'in-app':
            return Object.assign({}, NotificationInAppRequestFromJSONTyped(json, true), { type: 'in-app' } as const);
        default:
            return json;
    }
}

export function NotificationDispatchRequestToJSON(json: any): any {
    return NotificationDispatchRequestToJSONTyped(json, false);
}

export function NotificationDispatchRequestToJSONTyped(value?: NotificationDispatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'bulk':
            return Object.assign({}, NotificationBulkRequestToJSON(value), { type: 'bulk' } as const);
        case 'email':
            return Object.assign({}, NotificationEmailRequestToJSON(value), { type: 'email' } as const);
        case 'in-app':
            return Object.assign({}, NotificationInAppRequestToJSON(value), { type: 'in-app' } as const);
        default:
            return json;
    }
}

