/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationPagination
 */
export interface NotificationPagination {
    /**
     * 
     * @type {number}
     * @memberof NotificationPagination
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof NotificationPagination
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof NotificationPagination
     */
    total: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationPagination
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the NotificationPagination interface.
 */
export function instanceOfNotificationPagination(value: object): value is NotificationPagination {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function NotificationPaginationFromJSON(json: any): NotificationPagination {
    return NotificationPaginationFromJSONTyped(json, false);
}

export function NotificationPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'limit': json['limit'],
        'total': json['total'],
        'hasMore': json['hasMore'],
    };
}

export function NotificationPaginationToJSON(json: any): NotificationPagination {
    return NotificationPaginationToJSONTyped(json, false);
}

export function NotificationPaginationToJSONTyped(value?: NotificationPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'hasMore': value['hasMore'],
    };
}

