/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentReceiptResponse
 */
export interface PaymentReceiptResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the PaymentReceiptResponse interface.
 */
export function instanceOfPaymentReceiptResponse(value: object): value is PaymentReceiptResponse {
    return true;
}

export function PaymentReceiptResponseFromJSON(json: any): PaymentReceiptResponse {
    return PaymentReceiptResponseFromJSONTyped(json, false);
}

export function PaymentReceiptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentReceiptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PaymentReceiptResponseToJSON(json: any): PaymentReceiptResponse {
    return PaymentReceiptResponseToJSONTyped(json, false);
}

export function PaymentReceiptResponseToJSONTyped(value?: PaymentReceiptResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

