/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentLineItem
 */
export interface PaymentLineItem {
    /**
     * 
     * @type {string}
     * @memberof PaymentLineItem
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentLineItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentLineItem
     */
    unitAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentLineItem
     */
    totalAmount?: number;
}

/**
 * Check if a given object implements the PaymentLineItem interface.
 */
export function instanceOfPaymentLineItem(value: object): value is PaymentLineItem {
    return true;
}

export function PaymentLineItemFromJSON(json: any): PaymentLineItem {
    return PaymentLineItemFromJSONTyped(json, false);
}

export function PaymentLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentLineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'unitAmount': json['unitAmount'] == null ? undefined : json['unitAmount'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
    };
}

export function PaymentLineItemToJSON(json: any): PaymentLineItem {
    return PaymentLineItemToJSONTyped(json, false);
}

export function PaymentLineItemToJSONTyped(value?: PaymentLineItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'quantity': value['quantity'],
        'unitAmount': value['unitAmount'],
        'totalAmount': value['totalAmount'],
    };
}

