/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentLineItem } from './PaymentLineItem';
import {
    PaymentLineItemFromJSON,
    PaymentLineItemFromJSONTyped,
    PaymentLineItemToJSON,
    PaymentLineItemToJSONTyped,
} from './PaymentLineItem';

/**
 * 
 * @export
 * @interface PaymentReceiptRequest
 */
export interface PaymentReceiptRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    customerEmail: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    customerName: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    paymentId: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentReceiptRequest
     */
    amountPaid: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    currency: string;
    /**
     * 
     * @type {Date}
     * @memberof PaymentReceiptRequest
     */
    paymentDate?: Date;
    /**
     * 
     * @type {Array<PaymentLineItem>}
     * @memberof PaymentReceiptRequest
     */
    items?: Array<PaymentLineItem>;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    businessName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    supportEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    billingAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentReceiptRequest
     */
    notes?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentReceiptRequest
     */
    subtotalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentReceiptRequest
     */
    taxAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentReceiptRequest
     */
    discountAmount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentReceiptRequest
     */
    sendCopyTo?: Array<string>;
}

/**
 * Check if a given object implements the PaymentReceiptRequest interface.
 */
export function instanceOfPaymentReceiptRequest(value: object): value is PaymentReceiptRequest {
    if (!('customerEmail' in value) || value['customerEmail'] === undefined) return false;
    if (!('customerName' in value) || value['customerName'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('amountPaid' in value) || value['amountPaid'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function PaymentReceiptRequestFromJSON(json: any): PaymentReceiptRequest {
    return PaymentReceiptRequestFromJSONTyped(json, false);
}

export function PaymentReceiptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentReceiptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerEmail': json['customerEmail'],
        'customerName': json['customerName'],
        'paymentId': json['paymentId'],
        'amountPaid': json['amountPaid'],
        'currency': json['currency'],
        'paymentDate': json['paymentDate'] == null ? undefined : (new Date(json['paymentDate'])),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(PaymentLineItemFromJSON)),
        'businessName': json['businessName'] == null ? undefined : json['businessName'],
        'supportEmail': json['supportEmail'] == null ? undefined : json['supportEmail'],
        'billingAddress': json['billingAddress'] == null ? undefined : json['billingAddress'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'subtotalAmount': json['subtotalAmount'] == null ? undefined : json['subtotalAmount'],
        'taxAmount': json['taxAmount'] == null ? undefined : json['taxAmount'],
        'discountAmount': json['discountAmount'] == null ? undefined : json['discountAmount'],
        'sendCopyTo': json['sendCopyTo'] == null ? undefined : json['sendCopyTo'],
    };
}

export function PaymentReceiptRequestToJSON(json: any): PaymentReceiptRequest {
    return PaymentReceiptRequestToJSONTyped(json, false);
}

export function PaymentReceiptRequestToJSONTyped(value?: PaymentReceiptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerEmail': value['customerEmail'],
        'customerName': value['customerName'],
        'paymentId': value['paymentId'],
        'amountPaid': value['amountPaid'],
        'currency': value['currency'],
        'paymentDate': value['paymentDate'] == null ? undefined : ((value['paymentDate']).toISOString()),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(PaymentLineItemToJSON)),
        'businessName': value['businessName'],
        'supportEmail': value['supportEmail'],
        'billingAddress': value['billingAddress'],
        'notes': value['notes'],
        'subtotalAmount': value['subtotalAmount'],
        'taxAmount': value['taxAmount'],
        'discountAmount': value['discountAmount'],
        'sendCopyTo': value['sendCopyTo'],
    };
}

