/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Raw response returned by the Resend SDK.
 * @export
 * @interface ResendEmailResponse
 */
export interface ResendEmailResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ResendEmailResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the ResendEmailResponse interface.
 */
export function instanceOfResendEmailResponse(value: object): value is ResendEmailResponse {
    return true;
}

export function ResendEmailResponseFromJSON(json: any): ResendEmailResponse {
    return ResendEmailResponseFromJSONTyped(json, false);
}

export function ResendEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ResendEmailResponseToJSON(json: any): ResendEmailResponse {
    return ResendEmailResponseToJSONTyped(json, false);
}

export function ResendEmailResponseToJSONTyped(value?: ResendEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
    };
}

