/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeEvent
 */
export interface StripeEvent {
    /**
     * 
     * @type {string}
     * @memberof StripeEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StripeEvent
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof StripeEvent
     */
    object: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StripeEvent
     */
    data?: { [key: string]: any; };
    /**
     * Unix timestamp for when the event was created.
     * @type {number}
     * @memberof StripeEvent
     */
    created?: number;
}

/**
 * Check if a given object implements the StripeEvent interface.
 */
export function instanceOfStripeEvent(value: object): value is StripeEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    return true;
}

export function StripeEventFromJSON(json: any): StripeEvent {
    return StripeEventFromJSONTyped(json, false);
}

export function StripeEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'object': json['object'],
        'data': json['data'] == null ? undefined : json['data'],
        'created': json['created'] == null ? undefined : json['created'],
    };
}

export function StripeEventToJSON(json: any): StripeEvent {
    return StripeEventToJSONTyped(json, false);
}

export function StripeEventToJSONTyped(value?: StripeEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'object': value['object'],
        'data': value['data'],
        'created': value['created'],
    };
}

