/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorResponseAllOfDetails } from './ValidationErrorResponseAllOfDetails';
import {
    ValidationErrorResponseAllOfDetailsFromJSON,
    ValidationErrorResponseAllOfDetailsFromJSONTyped,
    ValidationErrorResponseAllOfDetailsToJSON,
    ValidationErrorResponseAllOfDetailsToJSONTyped,
} from './ValidationErrorResponseAllOfDetails';

/**
 * 
 * @export
 * @interface ValidationErrorResponse
 */
export interface ValidationErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponse
     */
    error: string;
    /**
     * 
     * @type {ValidationErrorResponseAllOfDetails}
     * @memberof ValidationErrorResponse
     */
    details?: ValidationErrorResponseAllOfDetails;
}

/**
 * Check if a given object implements the ValidationErrorResponse interface.
 */
export function instanceOfValidationErrorResponse(value: object): value is ValidationErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ValidationErrorResponseFromJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseFromJSONTyped(json, false);
}

export function ValidationErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'details': json['details'] == null ? undefined : ValidationErrorResponseAllOfDetailsFromJSON(json['details']),
    };
}

export function ValidationErrorResponseToJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseToJSONTyped(json, false);
}

export function ValidationErrorResponseToJSONTyped(value?: ValidationErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'details': ValidationErrorResponseAllOfDetailsToJSON(value['details']),
    };
}

