/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorResponseAllOfDetails
 */
export interface ValidationErrorResponseAllOfDetails {
    [key: string]: any | any;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ValidationErrorResponseAllOfDetails
     */
    fieldErrors?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidationErrorResponseAllOfDetails
     */
    formErrors?: Array<string>;
}

/**
 * Check if a given object implements the ValidationErrorResponseAllOfDetails interface.
 */
export function instanceOfValidationErrorResponseAllOfDetails(value: object): value is ValidationErrorResponseAllOfDetails {
    return true;
}

export function ValidationErrorResponseAllOfDetailsFromJSON(json: any): ValidationErrorResponseAllOfDetails {
    return ValidationErrorResponseAllOfDetailsFromJSONTyped(json, false);
}

export function ValidationErrorResponseAllOfDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponseAllOfDetails {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fieldErrors': json['fieldErrors'] == null ? undefined : json['fieldErrors'],
        'formErrors': json['formErrors'] == null ? undefined : json['formErrors'],
    };
}

export function ValidationErrorResponseAllOfDetailsToJSON(json: any): ValidationErrorResponseAllOfDetails {
    return ValidationErrorResponseAllOfDetailsToJSONTyped(json, false);
}

export function ValidationErrorResponseAllOfDetailsToJSONTyped(value?: ValidationErrorResponseAllOfDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'fieldErrors': value['fieldErrors'],
        'formErrors': value['formErrors'],
    };
}

