import { Resend } from 'resend'
import { format } from 'date-fns'

import { type TypedSupabaseClient } from '@/utils/typed-supabase-client'
import { logVisitorAuditEvent } from '@/lib/visitors/repository'
import { type VisitorProfile, type VisitorRuleRecord, type UnitRecord } from '@/lib/visitors/repository'
import { type TablesUpdate } from '@/lib/supabase'

export type NotificationContext = 'submission' | 'cancellation' | 'approval' | 'denial'

export interface VisitorNotificationPayload {
  supabase: TypedSupabaseClient
  logId: string
  actor: VisitorProfile
  host: VisitorProfile
  unit: UnitRecord
  rule: VisitorRuleRecord | null
  roommates: VisitorProfile[]
  manager: VisitorProfile | null
  status: 'pending' | 'approved' | 'denied' | 'cancelled' | 'completed'
  context: NotificationContext
  summary: string
  notifyHost?: boolean
  notifyRoommates?: boolean
  notifyManager?: boolean
  note?: string | null
}

function uniqueRecipients(recipients: VisitorProfile[]): VisitorProfile[] {
  const seen = new Set<string>()
  return recipients.filter((recipient) => {
    if (!recipient.email) {
      return false
    }
    const key = recipient.email.toLowerCase()
    if (seen.has(key)) {
      return false
    }
    seen.add(key)
    return true
  })
}

function buildSubject(context: NotificationContext, unit: UnitRecord): string {
  const unitLabel = `${unit.building_name} ${unit.unit_number}`.trim()

  switch (context) {
    case 'submission':
      return `New visitor request for ${unitLabel}`
    case 'cancellation':
      return `Visitor stay cancelled for ${unitLabel}`
    case 'approval':
      return `Visitor request approved – ${unitLabel}`
    case 'denial':
      return `Visitor request denied – ${unitLabel}`
    default:
      return `Visitor update for ${unitLabel}`
  }
}

function buildMessage(payload: VisitorNotificationPayload): string {
  const { host, unit, summary, context, note } = payload
  const unitLabel = `${unit.building_name} ${unit.unit_number}`.trim()

  const baseLines = [
    summary,
    `Unit: ${unitLabel}`,
    `Host roommate: ${host.full_name ?? 'Unknown tenant'}`,
  ]

  if (note) {
    baseLines.push(`Additional notes: ${note}`)
  }

  if (context === 'submission' && payload.rule) {
    baseLines.push(
      `Consecutive night limit: ${payload.rule.max_consecutive_nights} • Monthly max: ${
        payload.rule.max_visitors_per_month ?? 'Unlimited'
      }`,
    )
  }

  baseLines.push('This notification was generated by Share House Portal.')

  return baseLines.join('\n')
}

export async function sendVisitorNotification(payload: VisitorNotificationPayload): Promise<void> {
  const {
    supabase,
    logId,
    actor,
    host,
    unit,
    roommates,
    manager,
    status,
    context,
    summary,
    notifyHost = false,
    notifyRoommates = true,
    notifyManager = true,
  } = payload

  const recipients: VisitorProfile[] = []

  if (notifyRoommates) {
    roommates
      .filter((roommate) => roommate.id !== actor.id)
      .forEach((roommate) => {
        recipients.push(roommate)
      })
  }

  if (notifyManager && manager && manager.id !== actor.id) {
    recipients.push(manager)
  }

  if (notifyHost && host.id !== actor.id) {
    recipients.push(host)
  }

  const unique = uniqueRecipients(recipients)
  const addresses = unique.map((recipient) => recipient.email!).filter(Boolean)
  const subject = buildSubject(context, unit)
  const message = buildMessage(payload)

  const resendKey = process.env.RESEND_API_KEY
  let emailResult: string | null = null

  if (resendKey && addresses.length > 0) {
    try {
      const resend = new Resend(resendKey)
      await resend.emails.send({
        from: 'Share House Portal <notifications@example.com>',
        to: addresses,
        subject,
        text: message,
      })
      emailResult = `Notification dispatched to ${addresses.join(', ')}`
    } catch (error) {
      const reason = error instanceof Error ? error.message : 'Unknown error'
      emailResult = `Notification failed: ${reason}`
      console.error('Failed to send visitor notification', error)
    }
  } else if (addresses.length === 0) {
    emailResult = 'No eligible recipients to notify.'
  } else {
    emailResult = 'Email infrastructure unavailable – RESEND_API_KEY is not configured.'
  }

  const nowIso = new Date().toISOString()

  const update: TablesUpdate<'visitor_logs'> = {
    last_notification_at: nowIso,
    updated_at: nowIso,
  }

  if (notifyManager && manager) {
    update.property_manager_notified = true
  }

  try {
    await supabase.from('visitor_logs').update(update).eq('id', logId)
  } catch (error) {
    console.error('Failed to update notification timestamp for visitor log', error)
  }

  await logVisitorAuditEvent(supabase, {
    log_id: logId,
    event_type: `notification:${context}`,
    event_status: status,
    message: `${summary}${emailResult ? ` • ${emailResult}` : ''}`,
    performed_by: actor.id,
  })
}

export function formatStayWindow(arrival: string, departure: string): string {
  const arrivalDate = new Date(arrival)
  const departureDate = new Date(departure)

  if (Number.isNaN(arrivalDate.getTime()) || Number.isNaN(departureDate.getTime())) {
    return `${arrival} → ${departure}`
  }

  const formatToken = 'MMM d, yyyy'
  return `${format(arrivalDate, formatToken)} → ${format(departureDate, formatToken)}`
}
