/* tslint:disable */
/* eslint-disable */
/**
 * Share House Portal API
 * This OpenAPI document captures the request and response models implemented under `app/api/_**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BillingPortalRequest,
  BillingPortalResponse,
  CheckoutSessionRequest,
  CheckoutSessionResponse,
  DocumentListResponse,
  ErrorResponse,
  NotificationDispatchRequest,
  NotificationDispatchResponse,
  NotificationListResponse,
  PaymentReceiptRequest,
  PaymentReceiptResponse,
  ResendEmailResponse,
  StripeEvent,
  ValidationErrorResponse,
} from '../models/index';
import {
    BillingPortalRequestFromJSON,
    BillingPortalRequestToJSON,
    BillingPortalResponseFromJSON,
    BillingPortalResponseToJSON,
    CheckoutSessionRequestFromJSON,
    CheckoutSessionRequestToJSON,
    CheckoutSessionResponseFromJSON,
    CheckoutSessionResponseToJSON,
    DocumentListResponseFromJSON,
    DocumentListResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    NotificationDispatchRequestFromJSON,
    NotificationDispatchRequestToJSON,
    NotificationDispatchResponseFromJSON,
    NotificationDispatchResponseToJSON,
    NotificationListResponseFromJSON,
    NotificationListResponseToJSON,
    PaymentReceiptRequestFromJSON,
    PaymentReceiptRequestToJSON,
    PaymentReceiptResponseFromJSON,
    PaymentReceiptResponseToJSON,
    ResendEmailResponseFromJSON,
    ResendEmailResponseToJSON,
    StripeEventFromJSON,
    StripeEventToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateBillingPortalSessionRequest {
    billingPortalRequest: BillingPortalRequest;
}

export interface CreateCheckoutSessionRequest {
    checkoutSessionRequest: CheckoutSessionRequest;
}

export interface GetAuthCallbackRequest {
    accessToken?: string;
    refreshToken?: string;
}

export interface GetAuthGoogleRequest {
    code?: string;
    next?: string;
}

export interface GetSupabaseSidCallbackRequest {
    code?: string;
}

export interface HandleStripeWebhookRequest {
    stripeEvent: StripeEvent;
}

export interface ListDocumentsRequest {
    revision?: ListDocumentsRevisionEnum;
}

export interface ListNotificationsRequest {
    startDate?: Date;
    endDate?: Date;
    limit?: number;
    page?: number;
}

export interface SendNotificationRequest {
    notificationDispatchRequest: NotificationDispatchRequest;
}

export interface SendPaymentReceiptRequest {
    paymentReceiptRequest: PaymentReceiptRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Create a Stripe Billing Portal session
     */
    async createBillingPortalSessionRaw(requestParameters: CreateBillingPortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingPortalResponse>> {
        if (requestParameters['billingPortalRequest'] == null) {
            throw new runtime.RequiredError(
                'billingPortalRequest',
                'Required parameter "billingPortalRequest" was null or undefined when calling createBillingPortalSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/stripe/billing-portal`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BillingPortalRequestToJSON(requestParameters['billingPortalRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BillingPortalResponseFromJSON(jsonValue));
    }

    /**
     * Create a Stripe Billing Portal session
     */
    async createBillingPortalSession(requestParameters: CreateBillingPortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingPortalResponse> {
        const response = await this.createBillingPortalSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a Stripe Checkout session
     */
    async createCheckoutSessionRaw(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionResponse>> {
        if (requestParameters['checkoutSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'checkoutSessionRequest',
                'Required parameter "checkoutSessionRequest" was null or undefined when calling createCheckoutSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/stripe/checkout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckoutSessionRequestToJSON(requestParameters['checkoutSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create a Stripe Checkout session
     */
    async createCheckoutSession(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionResponse> {
        const response = await this.createCheckoutSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finalizes the OAuth flow by persisting the refresh token associated with the signed-in Supabase user. Redirects to the application shell when successful. 
     * Complete Supabase OAuth callback
     */
    async getAuthCallbackRaw(requestParameters: GetAuthCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['accessToken'] != null) {
            queryParameters['access_token'] = requestParameters['accessToken'];
        }

        if (requestParameters['refreshToken'] != null) {
            queryParameters['refresh_token'] = requestParameters['refreshToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/auth/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Finalizes the OAuth flow by persisting the refresh token associated with the signed-in Supabase user. Redirects to the application shell when successful. 
     * Complete Supabase OAuth callback
     */
    async getAuthCallback(requestParameters: GetAuthCallbackRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAuthCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Starts the Google OAuth sign-in flow handled by Supabase. Successful calls redirect the requester to the Supabase hosted OAuth consent screen and eventually back to the provided `next` path. 
     * Initiate Google OAuth via Supabase
     */
    async getAuthGoogleRaw(requestParameters: GetAuthGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['next'] != null) {
            queryParameters['next'] = requestParameters['next'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/auth/google`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Starts the Google OAuth sign-in flow handled by Supabase. Successful calls redirect the requester to the Supabase hosted OAuth consent screen and eventually back to the provided `next` path. 
     * Initiate Google OAuth via Supabase
     */
    async getAuthGoogle(requestParameters: GetAuthGoogleRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAuthGoogleRaw(requestParameters, initOverrides);
    }

    /**
     * Exchange a Supabase auth code for a session cookie
     */
    async getSupabaseSidCallbackRaw(requestParameters: GetSupabaseSidCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sid/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Exchange a Supabase auth code for a session cookie
     */
    async getSupabaseSidCallback(requestParameters: GetSupabaseSidCallbackRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getSupabaseSidCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Validates the Stripe signature header and stores payment artefacts in Supabase.
     * Process incoming Stripe webhook events
     */
    async handleStripeWebhookRaw(requestParameters: HandleStripeWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['stripeEvent'] == null) {
            throw new runtime.RequiredError(
                'stripeEvent',
                'Required parameter "stripeEvent" was null or undefined when calling handleStripeWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/stripe/webhook`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StripeEventToJSON(requestParameters['stripeEvent']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Validates the Stripe signature header and stores payment artefacts in Supabase.
     * Process incoming Stripe webhook events
     */
    async handleStripeWebhook(requestParameters: HandleStripeWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.handleStripeWebhookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns cached document metadata with support for revision snapshots and conditional requests.
     * List published tenant documents
     */
    async listDocumentsRaw(requestParameters: ListDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['revision'] != null) {
            queryParameters['revision'] = requestParameters['revision'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/documents`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentListResponseFromJSON(jsonValue));
    }

    /**
     * Returns cached document metadata with support for revision snapshots and conditional requests.
     * List published tenant documents
     */
    async listDocuments(requestParameters: ListDocumentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentListResponse> {
        const response = await this.listDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Filters notifications by optional date range, page, and limit parameters.
     * Retrieve notifications for the authenticated user
     */
    async listNotificationsRaw(requestParameters: ListNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = (requestParameters['endDate'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/notifications`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationListResponseFromJSON(jsonValue));
    }

    /**
     * Filters notifications by optional date range, page, and limit parameters.
     * Retrieve notifications for the authenticated user
     */
    async listNotifications(requestParameters: ListNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationListResponse> {
        const response = await this.listNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Routes a validated notification payload to the configured provider or Supabase storage.
     * Dispatch notifications through email and in-app channels
     */
    async sendNotificationRaw(requestParameters: SendNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationDispatchResponse>> {
        if (requestParameters['notificationDispatchRequest'] == null) {
            throw new runtime.RequiredError(
                'notificationDispatchRequest',
                'Required parameter "notificationDispatchRequest" was null or undefined when calling sendNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/notifications`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationDispatchRequestToJSON(requestParameters['notificationDispatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationDispatchResponseFromJSON(jsonValue));
    }

    /**
     * Routes a validated notification payload to the configured provider or Supabase storage.
     * Dispatch notifications through email and in-app channels
     */
    async sendNotification(requestParameters: SendNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationDispatchResponse> {
        const response = await this.sendNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Email a structured payment receipt via Resend
     */
    async sendPaymentReceiptRaw(requestParameters: SendPaymentReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentReceiptResponse>> {
        if (requestParameters['paymentReceiptRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentReceiptRequest',
                'Required parameter "paymentReceiptRequest" was null or undefined when calling sendPaymentReceipt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/payments/receipt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentReceiptRequestToJSON(requestParameters['paymentReceiptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentReceiptResponseFromJSON(jsonValue));
    }

    /**
     * Email a structured payment receipt via Resend
     */
    async sendPaymentReceipt(requestParameters: SendPaymentReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentReceiptResponse> {
        const response = await this.sendPaymentReceiptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Development-only helper that exercises the Resend integration with a canned payload.
     * Send a static sample email
     */
    async sendSampleEmailRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResendEmailResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/send`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResendEmailResponseFromJSON(jsonValue));
    }

    /**
     * Development-only helper that exercises the Resend integration with a canned payload.
     * Send a static sample email
     */
    async sendSampleEmail(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResendEmailResponse> {
        const response = await this.sendSampleEmailRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListDocumentsRevisionEnum = {
    Current: 'current',
    Revision2: 'revision2'
} as const;
export type ListDocumentsRevisionEnum = typeof ListDocumentsRevisionEnum[keyof typeof ListDocumentsRevisionEnum];
