// <auto-generated />
using System;
using DirectoryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DirectoryService.Data.Migrations
{
    [DbContext(typeof(DirectoryContext))]
    partial class DirectoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("DirectoryService.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("UnitId");

                    b.HasIndex("BuildingId", "AccountNumber")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b37db1c-3ee5-4754-9f0b-0a7b1d3aa1ef"),
                            AccountNumber = "MAIN-101-001",
                            Balance = 150.00m,
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UnitId = new Guid("7a81ce9b-889e-4f50-8f0a-1c9ce0597a80")
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingId", "PerformedAtUtc");

                    b.ToTable("AuditLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("61f59f0e-d904-42ea-86eb-132cd550ccaa"),
                            Action = "Seed",
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            Changes = "{\"AccountCreated\":true}",
                            CorrelationId = "seed-boot",
                            EntityId = new Guid("8b37db1c-3ee5-4754-9f0b-0a7b1d3aa1ef"),
                            EntityName = "Account",
                            PerformedAtUtc = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PerformedBy = "system-seed"
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Buildings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            AddressLine1 = "123 Main Street",
                            City = "Metropolis",
                            Code = "MAIN",
                            CreatedAtUtc = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Main Street Building",
                            PostalCode = "10001",
                            State = "NY"
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("927153ee-6355-4c24-8873-5014a4f14f7c"),
                            Description = "Create, update, and archive tenant accounts",
                            Name = "ManageAccounts"
                        },
                        new
                        {
                            Id = new Guid("332f15d0-06c7-4ffa-8a19-0a6c8b3d7a71"),
                            Description = "Maintain resident rosters and contact information",
                            Name = "ManageResidents"
                        },
                        new
                        {
                            Id = new Guid("9d61ac16-9dba-4a98-91df-46e4b2a938c9"),
                            Description = "Access and review audit log history",
                            Name = "ViewAuditTrail"
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MoveInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MoveOutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingId", "Email");

                    b.ToTable("Residents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5963f7c1-65eb-4de4-b4da-1df64e68545e"),
                            AccountId = new Guid("8b37db1c-3ee5-4754-9f0b-0a7b1d3aa1ef"),
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            Email = "jamie.rivera@example.com",
                            FirstName = "Jamie",
                            IsPrimary = true,
                            LastName = "Rivera",
                            MoveInDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "+1-555-0101"
                        },
                        new
                        {
                            Id = new Guid("e1808b68-75ad-4f14-8c1e-805d6e7a3f13"),
                            AccountId = new Guid("8b37db1c-3ee5-4754-9f0b-0a7b1d3aa1ef"),
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            Email = "alex.rivera@example.com",
                            FirstName = "Alex",
                            IsPrimary = false,
                            LastName = "Rivera",
                            MoveInDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "+1-555-0102"
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("132f35a0-476e-4b0a-863d-72f4c2cd7e5b"),
                            Description = "Oversees building operations and tenant lifecycle",
                            Name = "PropertyManager"
                        },
                        new
                        {
                            Id = new Guid("ff5c4ee4-a6f5-4e01-8ac8-11ac5f2dfc25"),
                            Description = "Manages leasing workflows and resident onboarding",
                            Name = "LeasingAgent"
                        },
                        new
                        {
                            Id = new Guid("8f7c7c87-5457-4f2d-8803-144612e3a59a"),
                            Description = "Handles maintenance requests and building upkeep",
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("132f35a0-476e-4b0a-863d-72f4c2cd7e5b"),
                            PermissionId = new Guid("927153ee-6355-4c24-8873-5014a4f14f7c")
                        },
                        new
                        {
                            RoleId = new Guid("132f35a0-476e-4b0a-863d-72f4c2cd7e5b"),
                            PermissionId = new Guid("332f15d0-06c7-4ffa-8a19-0a6c8b3d7a71")
                        },
                        new
                        {
                            RoleId = new Guid("132f35a0-476e-4b0a-863d-72f4c2cd7e5b"),
                            PermissionId = new Guid("9d61ac16-9dba-4a98-91df-46e4b2a938c9")
                        },
                        new
                        {
                            RoleId = new Guid("ff5c4ee4-a6f5-4e01-8ac8-11ac5f2dfc25"),
                            PermissionId = new Guid("927153ee-6355-4c24-8873-5014a4f14f7c")
                        },
                        new
                        {
                            RoleId = new Guid("ff5c4ee4-a6f5-4e01-8ac8-11ac5f2dfc25"),
                            PermissionId = new Guid("332f15d0-06c7-4ffa-8a19-0a6c8b3d7a71")
                        },
                        new
                        {
                            RoleId = new Guid("8f7c7c87-5457-4f2d-8803-144612e3a59a"),
                            PermissionId = new Guid("332f15d0-06c7-4ffa-8a19-0a6c8b3d7a71")
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingId", "Email")
                        .IsUnique();

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("63bb7e58-8c0f-4e7d-bb04-740a2eb3f901"),
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            Email = "morgan.lee@example.com",
                            FirstName = "Morgan",
                            HireDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Lee",
                            PhoneNumber = "+1-555-0201"
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.StaffRole", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId", "RoleId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RoleId");

                    b.ToTable("StaffRoles", (string)null);

                    b.HasData(
                        new
                        {
                            StaffId = new Guid("63bb7e58-8c0f-4e7d-bb04-740a2eb3f901"),
                            RoleId = new Guid("132f35a0-476e-4b0a-863d-72f4c2cd7e5b"),
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801")
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("Bedrooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquareFeet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(500);

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingId", "Identifier")
                        .IsUnique();

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a81ce9b-889e-4f50-8f0a-1c9ce0597a80"),
                            Bathrooms = 1,
                            Bedrooms = 2,
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            FloorNumber = 1,
                            Identifier = "101",
                            IsActive = true,
                            SquareFeet = 850
                        },
                        new
                        {
                            Id = new Guid("21f3d321-1a30-4b28-82f6-74a24a0e6f77"),
                            Bathrooms = 2,
                            Bedrooms = 3,
                            BuildingId = new Guid("2f2b1c4b-38c2-4f68-a54b-8c7fe1d6a801"),
                            FloorNumber = 1,
                            Identifier = "102",
                            IsActive = true,
                            SquareFeet = 1050
                        });
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Account", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Building", "Building")
                        .WithMany("Accounts")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DirectoryService.Data.Entities.Unit", "Unit")
                        .WithMany("Accounts")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Building", "Building")
                        .WithMany("AuditLogs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Resident", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Account", "Account")
                        .WithMany("Residents")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryService.Data.Entities.Building", "Building")
                        .WithMany("Residents")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryService.Data.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Staff", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Building", "Building")
                        .WithMany("StaffMembers")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.StaffRole", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryService.Data.Entities.Role", "Role")
                        .WithMany("StaffRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryService.Data.Entities.Staff", "Staff")
                        .WithMany("StaffRoles")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Unit", b =>
                {
                    b.HasOne("DirectoryService.Data.Entities.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Account", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Building", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AuditLogs");

                    b.Navigation("Residents");

                    b.Navigation("StaffMembers");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("StaffRoles");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Staff", b =>
                {
                    b.Navigation("StaffRoles");
                });

            modelBuilder.Entity("DirectoryService.Data.Entities.Unit", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
