# coding: utf-8

"""
    Share House Portal API

    This OpenAPI document captures the request and response models implemented under `app/api/**`. All routes are primarily intended for first-party clients and assume Supabase session cookies when authentication is required. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from share_house_portal_sdk.models.notification_bulk_request import NotificationBulkRequest
from share_house_portal_sdk.models.notification_email_request import NotificationEmailRequest
from share_house_portal_sdk.models.notification_in_app_request import NotificationInAppRequest
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

NOTIFICATIONDISPATCHREQUEST_ONE_OF_SCHEMAS = ["NotificationBulkRequest", "NotificationEmailRequest", "NotificationInAppRequest"]

class NotificationDispatchRequest(BaseModel):
    """
    NotificationDispatchRequest
    """
    # data type: NotificationEmailRequest
    oneof_schema_1_validator: Optional[NotificationEmailRequest] = None
    # data type: NotificationInAppRequest
    oneof_schema_2_validator: Optional[NotificationInAppRequest] = None
    # data type: NotificationBulkRequest
    oneof_schema_3_validator: Optional[NotificationBulkRequest] = None
    actual_instance: Optional[Union[NotificationBulkRequest, NotificationEmailRequest, NotificationInAppRequest]] = None
    one_of_schemas: Set[str] = { "NotificationBulkRequest", "NotificationEmailRequest", "NotificationInAppRequest" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = NotificationDispatchRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: NotificationEmailRequest
        if not isinstance(v, NotificationEmailRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationEmailRequest`")
        else:
            match += 1
        # validate data type: NotificationInAppRequest
        if not isinstance(v, NotificationInAppRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationInAppRequest`")
        else:
            match += 1
        # validate data type: NotificationBulkRequest
        if not isinstance(v, NotificationBulkRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotificationBulkRequest`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in NotificationDispatchRequest with oneOf schemas: NotificationBulkRequest, NotificationEmailRequest, NotificationInAppRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in NotificationDispatchRequest with oneOf schemas: NotificationBulkRequest, NotificationEmailRequest, NotificationInAppRequest. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into NotificationEmailRequest
        try:
            instance.actual_instance = NotificationEmailRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NotificationInAppRequest
        try:
            instance.actual_instance = NotificationInAppRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NotificationBulkRequest
        try:
            instance.actual_instance = NotificationBulkRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into NotificationDispatchRequest with oneOf schemas: NotificationBulkRequest, NotificationEmailRequest, NotificationInAppRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NotificationDispatchRequest with oneOf schemas: NotificationBulkRequest, NotificationEmailRequest, NotificationInAppRequest. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], NotificationBulkRequest, NotificationEmailRequest, NotificationInAppRequest]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


