import type { CatchUpBalance, PaymentReceiptHistoryEntry } from "@/types/payments"


export const catchUpBalances: CatchUpBalance[] = [
  {
    roommateId: "rm_avery",
    roommateName: "Avery Chen",
    unitLabel: "Unit 3B",
    currency: "USD",
    monthlyShare: 1260,
    autopayDay: 1,
    autopayStatus: "active",
    lastPaymentDate: "2024-05-28",
    lastPaymentAmount: 1260,
    charges: [
      {
        id: "rm_avery_rent_june",
        description: "June rent share",
        category: "rent",
        dueDate: "2024-06-01",
        originalAmount: 1260,
        outstandingAmount: 260,
      },
      {
        id: "rm_avery_wifi_june",
        description: "Wi-Fi reimbursement",
        category: "utilities",
        dueDate: "2024-06-12",
        originalAmount: 45,
        outstandingAmount: 45,
      },
      {
        id: "rm_avery_maintenance_june",
        description: "Community maintenance fee",
        category: "maintenance",
        dueDate: "2024-06-18",
        originalAmount: 30,
        outstandingAmount: 30,
      },
      {
        id: "rm_avery_deposit_topup",
        description: "Security deposit top-up",
        category: "deposit",
        dueDate: "2024-06-20",
        originalAmount: 300,
        outstandingAmount: 150,
      },
    ],
    contacts: {
      primary: {
        name: "Avery Chen",
        email: "avery.chen@example.com",
      },
      roommates: [
        { name: "Jordan Blake", email: "jordan.blake@example.com" },
        { name: "Priya Desai", email: "priya.desai@example.com" },
      ],
      propertyManager: {
        name: "Morgan Ellis",
        email: "morgan.ellis@sharehouse.example",
      },
    },
  },
  {
    roommateId: "rm_jordan",
    roommateName: "Jordan Blake",
    unitLabel: "Unit 3B",
    currency: "USD",
    monthlyShare: 1260,
    autopayDay: 1,
    autopayStatus: "paused",
    lastPaymentDate: "2024-05-12",
    lastPaymentAmount: 800,
    charges: [
      {
        id: "rm_jordan_rent_june",
        description: "June rent share",
        category: "rent",
        dueDate: "2024-06-01",
        originalAmount: 1260,
        outstandingAmount: 480,
      },
      {
        id: "rm_jordan_utilities_may",
        description: "Shared utilities true-up",
        category: "utilities",
        dueDate: "2024-06-10",
        originalAmount: 62,
        outstandingAmount: 62,
      },
      {
        id: "rm_jordan_parking_may",
        description: "Parking spot 17",
        category: "parking",
        dueDate: "2024-05-29",
        originalAmount: 80,
        outstandingAmount: 40,
      },
      {
        id: "rm_jordan_deposit_adjustment",
        description: "Deposit replenishment",
        category: "deposit",
        dueDate: "2024-06-25",
        originalAmount: 200,
        outstandingAmount: 80,
      },
    ],
    contacts: {
      primary: {
        name: "Jordan Blake",
        email: "jordan.blake@example.com",
      },
      roommates: [
        { name: "Avery Chen", email: "avery.chen@example.com" },
        { name: "Priya Desai", email: "priya.desai@example.com" },
      ],
      propertyManager: {
        name: "Morgan Ellis",
        email: "morgan.ellis@sharehouse.example",
      },
    },
  },
  {
    roommateId: "rm_priya",
    roommateName: "Priya Desai",
    unitLabel: "Unit 3B",
    currency: "USD",
    monthlyShare: 1260,
    autopayDay: 1,
    autopayStatus: "disabled",
    lastPaymentDate: "2024-04-30",
    lastPaymentAmount: 1260,
    charges: [
      {
        id: "rm_priya_rent_june",
        description: "June rent share",
        category: "rent",
        dueDate: "2024-06-01",
        originalAmount: 1260,
        outstandingAmount: 1260,
      },
      {
        id: "rm_priya_supplies_may",
        description: "Household supplies reimbursement",
        category: "fees",
        dueDate: "2024-06-08",
        originalAmount: 38,
        outstandingAmount: 38,
      },
      {
        id: "rm_priya_deposit_catchup",
        description: "Security deposit catch-up",
        category: "deposit",
        dueDate: "2024-06-22",
        originalAmount: 250,
        outstandingAmount: 200,
      },
    ],
    contacts: {
      primary: {
        name: "Priya Desai",
        email: "priya.desai@example.com",
      },
      roommates: [
        { name: "Avery Chen", email: "avery.chen@example.com" },
        { name: "Jordan Blake", email: "jordan.blake@example.com" },
      ],
      propertyManager: {
        name: "Morgan Ellis",
        email: "morgan.ellis@sharehouse.example",
      },
    },
  },
]

export const receiptHistory: PaymentReceiptHistoryEntry[] = [
  {
    id: "rcpt_avery_2024_06",
    issuedTo: "Avery Chen",
    paymentDate: "2024-06-01",
    periodStart: "2024-06-01",
    periodEnd: "2024-06-30",
    currency: "USD",
    amount: 1335,
    status: "paid",
    paymentMethod: "Visa •••• 4242 (Autopay)",
    receiptUrl: "https://receipts.roomsily.dev/rcpt_avery_2024_06.pdf",
    invoiceUrl: "https://receipts.roomsily.dev/invoice_avery_2024_06",
    taxReceiptUrl: "https://receipts.roomsily.dev/tax_avery_2024_ytd.pdf",
    memo: "Includes rent share plus reimbursable Wi-Fi and maintenance fees.",
    lineItems: [
      {
        id: "avery_rent_june",
        description: "June rent share",
        category: "rent",
        quantity: 1,
        unitAmount: 1260,
        totalAmount: 1260,
      },
      {
        id: "avery_wifi_june",
        description: "Wi-Fi reimbursement",
        category: "utilities",
        quantity: 1,
        unitAmount: 45,
        totalAmount: 45,
      },
      {
        id: "avery_maintenance_june",
        description: "Community maintenance fee",
        category: "maintenance",
        quantity: 1,
        unitAmount: 30,
        totalAmount: 30,
      },
    ],
  },
  {
    id: "rcpt_jordan_2024_05",
    issuedTo: "Jordan Blake",
    paymentDate: "2024-05-12",
    periodStart: "2024-05-01",
    periodEnd: "2024-05-31",
    currency: "USD",
    amount: 880,
    status: "paid",
    paymentMethod: "ACH checking •••• 1100",
    receiptUrl: "https://receipts.roomsily.dev/rcpt_jordan_2024_05.pdf",
    invoiceUrl: "https://receipts.roomsily.dev/invoice_jordan_2024_05",
    taxReceiptUrl: "https://receipts.roomsily.dev/tax_jordan_2024_ytd.pdf",
    memo: "Manual catch-up payment covering parking and partial rent.",
    lineItems: [
      {
        id: "jordan_rent_may",
        description: "May rent share (partial)",
        category: "rent",
        quantity: 1,
        unitAmount: 800,
        totalAmount: 800,
      },
      {
        id: "jordan_parking_may",
        description: "Parking spot 17",
        category: "parking",
        quantity: 1,
        unitAmount: 80,
        totalAmount: 80,
      },
    ],
  },
  {
    id: "rcpt_priya_2024_04",
    issuedTo: "Priya Desai",
    paymentDate: "2024-04-30",
    periodStart: "2024-04-01",
    periodEnd: "2024-04-30",
    currency: "USD",
    amount: 1260,
    status: "paid",
    paymentMethod: "Visa •••• 3188",
    receiptUrl: "https://receipts.roomsily.dev/rcpt_priya_2024_04.pdf",
    invoiceUrl: "https://receipts.roomsily.dev/invoice_priya_2024_04",
    taxReceiptUrl: "https://receipts.roomsily.dev/tax_priya_2024_ytd.pdf",
    memo: "Autopay rent receipt for April billing period.",
    lineItems: [
      {
        id: "priya_rent_april",
        description: "April rent share",
        category: "rent",
        quantity: 1,
        unitAmount: 1260,
        totalAmount: 1260,
      },
    ],
  },
  {
    id: "rcpt_unit_refund_2024_03",
    issuedTo: "Unit 3B",
    paymentDate: "2024-03-18",
    currency: "USD",
    amount: -60,
    status: "refunded",
    paymentMethod: "Roomsily credit",
    receiptUrl: "https://receipts.roomsily.dev/rcpt_unit_refund_2024_03.pdf",
    memo: "Refund issued after duplicate community maintenance charge.",
    lineItems: [
      {
        id: "unit_maintenance_refund",
        description: "Maintenance fee adjustment",
        category: "maintenance",
        quantity: 1,
        unitAmount: -60,
        totalAmount: -60,

      },
    ],
  },
]
