mode: deployment
replicaCount: 2
serviceAccount:
  create: true
  name: otel-collector
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/share-house-otel-collector
service:
  type: ClusterIP
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 400
      spike_limit_mib: 100
    batch:
      send_batch_size: 8192
      timeout: 5s
    k8sattributes:
      auth_type: serviceAccount
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
  exporters:
    logging:
      loglevel: warn
    datadog:
      api:
        key: "${env:DATADOG_API_KEY}"
        site: "${env:DATADOG_SITE}"
      traces:
        compute_stats_by_span_kind: true
      metrics:
        resource_attributes_as_tags: true
  service:
    telemetry:
      logs:
        level: info
      metrics:
        address: 0.0.0.0:8888
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [datadog]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [datadog]
extraEnvs:
  - name: DATADOG_SITE
    value: datadoghq.com
  - name: DATADOG_API_KEY
    valueFrom:
      secretKeyRef:
        name: datadog-api-key
        key: api-key
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
