-- Ensure support for range-based exclusion constraints used to prevent overlapping bookings.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Amenities available for residents to reserve.
CREATE TABLE public.amenities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  description text NULL,
  capacity integer NOT NULL,
  location text NULL,
  CONSTRAINT amenities_capacity_positive CHECK (capacity > 0)
);

COMMENT ON TABLE public.amenities IS 'Reservable amenities within the share house and their maximum capacity.';

-- House rules scoped to a particular amenity.
CREATE TABLE public.rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  amenity_id bigint NOT NULL REFERENCES public.amenities(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NULL,
  enforcement_level text NULL DEFAULT 'advisory'
);

CREATE INDEX rules_amenity_id_idx ON public.rules (amenity_id);

COMMENT ON TABLE public.rules IS 'Amenity-specific behavioural rules that residents must acknowledge before booking.';

-- Administrative blackout windows that prevent reservations.
CREATE TABLE public.blackouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  amenity_id bigint NOT NULL REFERENCES public.amenities(id) ON DELETE CASCADE,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  reason text NULL,
  CONSTRAINT blackouts_time_order CHECK (ends_at > starts_at)
);

-- Prevent overlapping blackout windows for a single amenity.
ALTER TABLE public.blackouts
  ADD CONSTRAINT blackouts_no_overlap
  EXCLUDE USING gist (
    amenity_id WITH =,
    tstzrange(starts_at, ends_at, '[)') WITH &&
  );

CREATE INDEX blackouts_amenity_id_idx ON public.blackouts (amenity_id);

COMMENT ON TABLE public.blackouts IS 'Time ranges where an amenity is unavailable; enforced to be non-overlapping per amenity.';

-- Resident reservations for amenities.
CREATE TABLE public.reservations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  amenity_id bigint NOT NULL REFERENCES public.amenities(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  attendee_count integer NOT NULL,
  notes text NULL,
  CONSTRAINT reservations_time_order CHECK (ends_at > starts_at),
  CONSTRAINT reservations_attendee_positive CHECK (attendee_count > 0)
);

-- Enforce uniqueness of time ranges per amenity to avoid double bookings.
ALTER TABLE public.reservations
  ADD CONSTRAINT reservations_no_overlap
  EXCLUDE USING gist (
    amenity_id WITH =,
    tstzrange(starts_at, ends_at, '[)') WITH &&
  );

CREATE INDEX reservations_amenity_id_idx ON public.reservations (amenity_id);
CREATE INDEX reservations_profile_id_idx ON public.reservations (profile_id);

COMMENT ON TABLE public.reservations IS 'Amenity bookings. Time-slot conflicts are prevented via a GiST exclusion constraint and trigger-based capacity checks described below.';

-- Validate that reservation attendance never exceeds amenity capacity nor overlaps with blackouts.
CREATE OR REPLACE FUNCTION public.validate_reservation_capacity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  max_capacity integer;
  overlapping_attendees integer;
  excluded_id bigint := NULL;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    excluded_id := OLD.id;
  END IF;

  SELECT capacity
    INTO max_capacity
  FROM public.amenities
  WHERE id = NEW.amenity_id
  FOR SHARE;

  IF max_capacity IS NULL THEN
    RAISE EXCEPTION 'Amenity % does not exist', NEW.amenity_id;
  END IF;

  IF NEW.attendee_count > max_capacity THEN
    RAISE EXCEPTION 'Reservation attendee count % exceeds amenity capacity %', NEW.attendee_count, max_capacity;
  END IF;

  SELECT COALESCE(sum(attendee_count), 0)
    INTO overlapping_attendees
  FROM public.reservations
  WHERE amenity_id = NEW.amenity_id
    AND (excluded_id IS NULL OR id <> excluded_id)
    AND tstzrange(starts_at, ends_at, '[)') && tstzrange(NEW.starts_at, NEW.ends_at, '[)');

  IF overlapping_attendees + NEW.attendee_count > max_capacity THEN
    RAISE EXCEPTION 'Combined attendance % exceeds amenity capacity %', overlapping_attendees + NEW.attendee_count, max_capacity;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.blackouts b
    WHERE b.amenity_id = NEW.amenity_id
      AND tstzrange(b.starts_at, b.ends_at, '[)') && tstzrange(NEW.starts_at, NEW.ends_at, '[)')
  ) THEN
    RAISE EXCEPTION 'Reservation conflicts with a blackout window for amenity %', NEW.amenity_id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER reservations_capacity_guard
BEFORE INSERT OR UPDATE ON public.reservations
FOR EACH ROW EXECUTE FUNCTION public.validate_reservation_capacity();

COMMENT ON FUNCTION public.validate_reservation_capacity() IS 'Prevents reservations that exceed amenity capacity or overlap blackouts; complements the GiST exclusion constraint to guarantee conflict-free bookings.';
COMMENT ON CONSTRAINT reservations_no_overlap ON public.reservations IS 'Uses tstzrange overlap detection to guarantee a unique reservation time slot per amenity.';
COMMENT ON CONSTRAINT blackouts_no_overlap ON public.blackouts IS 'Prevents overlapping administrative downtime windows for the same amenity.';
