-- Enforce per-member booking quotas on the meetings table.
-- A null member_id acts as the global default configuration.
create table if not exists public.booking_quota_settings (
  id bigint generated by default as identity primary key,
  member_id uuid references auth.users(id) on delete cascade,
  daily_limit integer not null check (daily_limit >= 0),
  weekly_limit integer not null check (weekly_limit >= 0),
  created_at timestamptz not null default now(),
  unique (member_id)
);

alter table public.booking_quota_settings enable row level security;

-- Allow service role management of quota settings. Application clients should
-- rely on stored procedures or admin tooling.
create policy if not exists "Service role can manage booking quota settings"
  on public.booking_quota_settings
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- Seed a default global configuration if one is not already present.
insert into public.booking_quota_settings (member_id, daily_limit, weekly_limit)
select null, 2, 5
where not exists (
  select 1
  from public.booking_quota_settings
  where member_id is null
);

create or replace function public.enforce_meeting_booking_quota()
returns trigger
language plpgsql
as
$$
declare
  quota record;
  day_start timestamptz := date_trunc('day', new.start_time);
  week_start timestamptz := date_trunc('week', new.start_time);
  daily_count integer;
  weekly_count integer;
begin
  -- Fetch the per-member override first, then fall back to the global default.
  select s.daily_limit, s.weekly_limit
  into quota
  from public.booking_quota_settings as s
  where s.member_id = new.user_id
  limit 1;

  if not found then
    select s.daily_limit, s.weekly_limit
    into quota
    from public.booking_quota_settings as s
    where s.member_id is null
    limit 1;
  end if;

  if quota is null then
    -- No quota configured; allow the insert.
    return new;
  end if;

  select count(*)
  into daily_count
  from public.meetings as m
  where m.user_id = new.user_id
    and m.start_time >= day_start
    and m.start_time < day_start + interval '1 day';

  if quota.daily_limit is not null and daily_count >= quota.daily_limit then
    raise exception using
      message = format(
        'Daily booking quota reached (%s bookings allowed per day).',
        quota.daily_limit
      ),
      detail = 'BOOKING_QUOTA_DAILY_LIMIT',
      errcode = 'P0001';
  end if;

  select count(*)
  into weekly_count
  from public.meetings as m
  where m.user_id = new.user_id
    and m.start_time >= week_start
    and m.start_time < week_start + interval '1 week';

  if quota.weekly_limit is not null and weekly_count >= quota.weekly_limit then
    raise exception using
      message = format(
        'Weekly booking quota reached (%s bookings allowed per week).',
        quota.weekly_limit
      ),
      detail = 'BOOKING_QUOTA_WEEKLY_LIMIT',
      errcode = 'P0001';
  end if;

  return new;
end;
$$;

-- Ensure we only have a single trigger definition applied to the meetings table.
drop trigger if exists trg_enforce_meeting_booking_quota on public.meetings;

create trigger trg_enforce_meeting_booking_quota
before insert on public.meetings
for each row
execute function public.enforce_meeting_booking_quota();
