CREATE TABLE public.chat (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL,
  path text NULL DEFAULT ''::text,
  sharepath text NULL,
  messages text[] NULL,
  title text NULL DEFAULT ''::text,
  profile_id text NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid()
) WITH (OIDS=FALSE);
ALTER TABLE public.chat ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.countries (
  id bigint primary key generated always as identity,
  name text NULL,
  iso2 text NOT NULL,
  iso3 text NOT NULL,
  local_name text NULL,
  continent public.continents NULL
) WITH (OIDS=FALSE);
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.inqueries (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL DEFAULT ''::text,
  email text NOT NULL DEFAULT ''::text,
  message text NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid()
) WITH (OIDS=FALSE);
ALTER TABLE public.inqueries ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.meetings (
  id bigint primary key generated always as identity,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  summary text NOT NULL,
  description text NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  meet_link text NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now()
) WITH (OIDS=FALSE);
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.members_table (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL DEFAULT ''::text,
  member_id uuid NOT NULL,
  email text NULL DEFAULT ''::text,
  password text NOT NULL DEFAULT ''::text
) WITH (OIDS=FALSE);
ALTER TABLE public.members_table ENABLE ROW LEVEL SECURITY;

create table public.profiles (
  id uuid not null default auth.uid (),
  updated_at timestamp with time zone null,
  username text null,
  full_name text null,
  avatar_url text null,
  website text null,
  email text null,
  waddress text null,
  xhandle text null,
  created_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  company text null,
  company_logo_url text null,
  job_title text null,
  linkedin_url text null,
  public_id uuid null,
  card_styles text null,
  card_style jsonb null,
  role text null default 'user'::text,
  constraint profiles_pkey primary key (id),
  constraint profiles_username_key unique (username),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint username_length check ((char_length(username) >= 3))
) TABLESPACE pg_default;

create index IF not exists idx_profiles_role on public.profiles using btree (role) TABLESPACE pg_default;

CREATE TABLE public.permission_table (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  role text NOT NULL,
  status text NOT NULL,
  member_id uuid NOT NULL,
  CONSTRAINT permission_table_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  task text NULL,
  is_complete boolean NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL DEFAULT ''::text,
  created_by uuid NOT NULL,
  CONSTRAINT todos_pkey PRIMARY KEY (id),
  CONSTRAINT todos_created_by_fkey FOREIGN KEY (created_by) REFERENCES members_table(member_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT todos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT todos_task_check CHECK ((char_length(task) > 3))
) TABLESPACE pg_default;

CREATE POLICY "Individuals can view their own permissions." ON public.permission_table FOR SELECT TO authenticated USING ((select auth.uid()) = member_id);
CREATE POLICY "Individuals can insert their own permissions." ON public.permission_table FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = member_id);
CREATE POLICY "Individuals can update their own permissions." ON public.permission_table FOR UPDATE TO authenticated USING ((select auth.uid()) = member_id) WITH CHECK ((select auth.uid()) = member_id);
CREATE POLICY "Individuals can delete their own permissions." ON public.permission_table FOR DELETE TO authenticated USING ((select auth.uid()) = member_id);

CREATE POLICY "Individuals can view their own todos." ON public.todos FOR SELECT TO authenticated USING ((select auth.uid()) = user_id);
CREATE POLICY "Individuals can insert their own todos." ON public.todos FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Individuals can update their own todos." ON public.todos FOR UPDATE TO authenticated USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Individuals can delete their own todos." ON public.todos FOR DELETE TO authenticated USING ((select auth.uid()) = user_id);

-- Communications service domain --------------------------------------------------------

create type public.announcement_status as enum ('draft', 'scheduled', 'published', 'archived');
create type public.bulletin_status as enum ('pending', 'approved', 'rejected', 'escalated', 'archived');
create type public.moderation_status as enum ('clean', 'under_review', 'action_required', 'resolved');
create type public.abuse_status as enum ('open', 'investigating', 'resolved');
create type public.survey_status as enum ('draft', 'open', 'closed', 'archived');
create type public.moderation_action as enum ('submit', 'approve', 'reject', 'escalate', 'resolve', 'flag');

CREATE TABLE public.communications_announcements (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  body text NOT NULL,
  status public.announcement_status NOT NULL DEFAULT 'draft',
  publish_at timestamp with time zone NULL,
  expire_at timestamp with time zone NULL,
  created_by uuid NOT NULL,
  target_roles text[] NULL,
  CONSTRAINT communications_announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE CASCADE
) WITH (OIDS=FALSE);
ALTER TABLE public.communications_announcements ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_communications_announcements_status ON public.communications_announcements(status);
CREATE INDEX IF NOT EXISTS idx_communications_announcements_publish_at ON public.communications_announcements(publish_at);

CREATE TABLE public.communications_bulletins (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  author_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  status public.bulletin_status NOT NULL DEFAULT 'pending',
  moderation_status public.moderation_status NOT NULL DEFAULT 'clean',
  abuse_reason text NULL,
  abuse_context jsonb NULL,
  moderated_by uuid NULL,
  moderated_at timestamp with time zone NULL,
  CONSTRAINT communications_bulletins_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  CONSTRAINT communications_bulletins_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.profiles(id) ON DELETE SET NULL
) WITH (OIDS=FALSE);
ALTER TABLE public.communications_bulletins ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_communications_bulletins_status ON public.communications_bulletins(status);
CREATE INDEX IF NOT EXISTS idx_communications_bulletins_moderation_status ON public.communications_bulletins(moderation_status);

CREATE TABLE public.communications_bulletin_audits (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  bulletin_id bigint NOT NULL,
  actor_id uuid NOT NULL,
  action public.moderation_action NOT NULL,
  notes text NULL,
  metadata jsonb NULL,
  CONSTRAINT communications_bulletin_audits_bulletin_id_fkey FOREIGN KEY (bulletin_id) REFERENCES public.communications_bulletins(id) ON DELETE CASCADE,
  CONSTRAINT communications_bulletin_audits_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id) ON DELETE CASCADE
) WITH (OIDS=FALSE);
ALTER TABLE public.communications_bulletin_audits ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.communications_abuse_reports (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  bulletin_id bigint NOT NULL,
  reporter_id uuid NOT NULL,
  status public.abuse_status NOT NULL DEFAULT 'open',
  reason text NOT NULL,
  details text NULL,
  resolved_at timestamp with time zone NULL,
  resolution_notes text NULL,
  CONSTRAINT communications_abuse_reports_bulletin_id_fkey FOREIGN KEY (bulletin_id) REFERENCES public.communications_bulletins(id) ON DELETE CASCADE,
  CONSTRAINT communications_abuse_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id) ON DELETE CASCADE
) WITH (OIDS=FALSE);
ALTER TABLE public.communications_abuse_reports ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_communications_abuse_reports_status ON public.communications_abuse_reports(status);

CREATE TABLE public.communications_surveys (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  description text NULL,
  status public.survey_status NOT NULL DEFAULT 'draft',
  questions jsonb NOT NULL,
  created_by uuid NOT NULL,
  closes_at timestamp with time zone NULL,
  metadata jsonb NULL,
  CONSTRAINT communications_surveys_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE CASCADE
) WITH (OIDS=FALSE);
ALTER TABLE public.communications_surveys ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_communications_surveys_status ON public.communications_surveys(status);

CREATE TABLE public.communications_survey_responses (
  id bigint primary key generated always as identity,
  survey_id bigint NOT NULL,
  respondent_id uuid NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  answers jsonb NOT NULL,
  metadata jsonb NULL,
  CONSTRAINT communications_survey_responses_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES public.communications_surveys(id) ON DELETE CASCADE,
  CONSTRAINT communications_survey_responses_respondent_id_fkey FOREIGN KEY (respondent_id) REFERENCES public.profiles(id) ON DELETE SET NULL
) WITH (OIDS=FALSE);
ALTER TABLE public.communications_survey_responses ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_communications_survey_responses_survey_id ON public.communications_survey_responses(survey_id);

-- RBAC aware policies rely on the profiles.role column populated via the application layer.
CREATE POLICY "Announcements visible to authenticated users" ON public.communications_announcements
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Announcements manageable by admins" ON public.communications_announcements
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Bulletins viewable when authored or approved" ON public.communications_bulletins
  FOR SELECT TO authenticated USING (
    author_id = auth.uid()
    OR status IN ('approved'::public.bulletin_status, 'escalated'::public.bulletin_status)
  );
CREATE POLICY "Bulletins insert by authenticated" ON public.communications_bulletins
  FOR INSERT TO authenticated WITH CHECK (author_id = auth.uid());
CREATE POLICY "Bulletins managed by admins" ON public.communications_bulletins
  FOR UPDATE TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Abuse reports readable by admins" ON public.communications_abuse_reports
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
    OR reporter_id = auth.uid()
  );
CREATE POLICY "Abuse reports insert by authenticated" ON public.communications_abuse_reports
  FOR INSERT TO authenticated WITH CHECK (reporter_id = auth.uid());

CREATE POLICY "Surveys readable to authenticated" ON public.communications_surveys
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Surveys managed by admins" ON public.communications_surveys
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

CREATE POLICY "Survey responses readable to admins or owners" ON public.communications_survey_responses
  FOR SELECT TO authenticated USING (
    respondent_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );
CREATE POLICY "Survey responses insert by authenticated" ON public.communications_survey_responses
  FOR INSERT TO authenticated WITH CHECK (true);

-- Remember to create any additional RLS policies tailored to your environment before using these tables with Supabase APIs.
